### ISSUE TITLE
Not works it

### ISSUE THREAD

**Issue by missjewel** [driftyco/ionic-proxy-example#1]
Hello I have a server API for example: http://localhost:3000/ 

I'm trying to access my api endpoint from my device does not work though and create a proxy, gulp tasks in addition to the constant. My mistake in the device tells mistake {data: null, status: 0 ......}

**Comment by Ionitron** [comment]
Greetings @missjewel!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
