### ISSUE TITLE
CORS not working in apk but works in ionic serve( browser)

### ISSUE THREAD

**Issue by iiitmahesh** [driftyco/ionic-proxy-example#2]
n ionic serve cors is working in browser but not working apk

. In the browser (using ionic serve) it was working properly , but in apk (using ionic build android ) it was not working........

cordova plugin add cordova-plugin-whitelist (I have added this puigin using CLI)

I have used these things in config.xml 

ionic.project
{
"name": "sampleApp",
"app_id": "a2fbab8f",
"proxies": [
{
"path": "/api",
"proxyUrl": "http://myserver/api"
}
]
}

**Comment by Ionitron** [comment]
Greetings @iiitmahesh!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by alanbarboza** [comment]
Maybe it has been solved?

**Comment by contactjavas** [comment]
i have this/similar issue in ionic 4 (beta 12)
